spring.application.name=LMS

# SERVER
server.port=8084

# MONGODB
spring.data.mongodb.uri=mongodb://localhost:27017/lmsdb

# THYMELEAF
spring.thymeleaf.cache=false

# FILE UPLOAD
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# UPLOAD FOLDER
file.upload-dir=uploads/

spring.web.resources.static-locations=classpath:/static/,file:uploads/


# ================= EMAIL =================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ravinamahariyamahariya@gmail.com
spring.mail.password=ckznfbsuebnwzmrp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true